/* 
 This file was generated by Dashcode and is covered by the 
 license.txt included in the project.  You may edit this file, 
 however it is recommended to first turn off the Dashcode 
 code generator otherwise the changes will be lost.
 */
var dashcodePartSpecs = {
    "about": { "text": "Developed by ntrifunovic", "view": "DC.Text" },
    "done": { "creationFunction": "CreateGlassButton", "onclick": "showFront", "text": "Done" },
    "DreamstimeAmount": { "text": "NA", "view": "DC.Text" },
    "DreamstimeText": { "text": "Dreamstime", "view": "DC.Text" },
    "FotoliaAmount": { "text": "NA", "view": "DC.Text" },
    "FotoliaText": { "text": "Fotolia", "view": "DC.Text" },
    "info": { "backgroundStyle": "black", "creationFunction": "CreateInfoButton", "foregroundStyle": "white", "frontID": "front", "onclick": "showBack" },
    "iStockAmount": { "text": "NA", "view": "DC.Text" },
    "iStockText": { "text": "iStock", "view": "DC.Text" },
    "line": { "text": "________________", "view": "DC.Text" },
    "line1": { "text": "________________", "view": "DC.Text" },
    "status": { "criticalValue": 3, "onValue": 1, "view": "DC.Indicator", "warningValue": 2 },
    "statusMask": { "view": "DC.Text" },
    "text": { "text": "Micro Stats", "view": "DC.Text" },
    "text1": { "text": "Click here to support this app by buying one of my images", "view": "DC.Text" },
    "topRectangleShape": { "creationFunction": "CreateShape", "leftImageWidth": 12, "rightImageWidth": 12 },
    "topRectangleShape1": { "creationFunction": "CreateShape", "leftImageWidth": 12, "rightImageWidth": 12 }
};










